"use client";

import { motion } from "framer-motion";
import { Card, Badge } from "@/components/ui/primitives";
import { Cite } from "@/components/evidence/Cite";
import { StoryClaim } from "@/lib/types";
import { Sparkles } from "lucide-react";

export function StoryMode({ claims, title = "Investigation Story" }: { claims: StoryClaim[]; title?: string }) {
  return (
    <Card initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="p-6">
      <div className="mb-1 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan/10 text-cyan">
            <Sparkles size={14} />
          </div>
          <h3 className="text-sm font-semibold text-text">{title}</h3>
        </div>
        <Badge tone="cyan" className="font-mono">Every sentence is cited</Badge>
      </div>
      <p className="mb-5 mt-1 text-xs leading-relaxed text-text-faint">
        Generated by deterministic rule engines and grounded LLM narration only — no claim below was invented; each
        cites the exact evidence record, confidence, and detection rule that produced it.
      </p>

      <div className="space-y-3">
        {claims.map((c, i) => (
          <motion.div
            key={c.id}
            initial={{ opacity: 0, x: -10 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ delay: i * 0.08, duration: 0.4 }}
            className="rounded-xl border border-border-soft bg-bg-raised p-4"
          >
            <p className="text-[13.5px] leading-relaxed text-text">
              {c.text} <Cite ids={c.evidenceIds} chipKey={c.id} />
            </p>
            <div className="mt-2.5 flex items-center gap-2 font-mono text-[10.5px] text-text-faint">
              <span className="rounded border border-cyan/20 bg-cyan-dim px-1.5 py-0.5 text-cyan">{c.rule}</span>
              <span>confidence {typeof c.confidence === "number" ? c.confidence.toFixed(2) : c.confidence}</span>
            </div>
          </motion.div>
        ))}
      </div>
    </Card>
  );
}
