"use client";

import { motion } from "framer-motion";
import { Card, Badge } from "@/components/ui/primitives";
import { Cite } from "@/components/evidence/Cite";
import { StoryClaim } from "@/lib/types";
import { Sparkles } from "lucide-react";

const citationTextPattern = /\s*\[[A-Za-z0-9_.-]+\]/g;

export function StoryMode({ claims, title = "Investigation Story" }: { claims: StoryClaim[]; title?: string }) {
  return (
    <Card initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }} className="p-6">
      <div className="mb-1 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-cyan/10 text-cyan">
            <Sparkles size={14} />
          </div>
          <h3 className="text-sm font-semibold text-text">{title}</h3>
        </div>
        <Badge tone="cyan" className="font-mono">Every sentence is cited</Badge>
      </div>
      <p className="mb-5 mt-1 text-xs leading-relaxed text-text-faint">
        Generated by deterministic rule engines and grounded LLM narration only — no claim below was invented; each
        cites the exact evidence record, confidence, and detection rule that produced it.
      </p>

      <motion.p
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="text-[13.5px] leading-relaxed text-text"
      >
        {claims.map((claim, index) => (
          <span key={claim.id}>
            {index > 0 ? " " : ""}
            {claim.text.replace(citationTextPattern, "")}{" "}
            <Cite ids={claim.evidenceIds} chipKey={claim.id} />
          </span>
        ))}
      </motion.p>
    </Card>
  );
}
